### PR TITLE
Add Corticotroph_JNP and Pituitary_MCE models

### PR DESCRIPTION
**Pull request by patrickfletcher**
Here is the initial commit for our two models. Let me know what you think.  In the future, I'd like to link it to CLODE but I don't think it's quite ready.

### CODE REVIEW

**Comment by artielbm** [comment]
These look good, but I would like links to the ode files in readme.md, so that if the readme.md is displayed as a web page instead of a blob, users can download the files.  Look at the links for paper #1 in my CV (Ha and Sherman, 2020).  - Artie

**Comment by patrickfletcher** [comment]
I've added the links.  The first link at the top (near XPPAUT link) goes to the folder, while I think clicking on the file names will directly open the ODE files.  I haven't tested it because the folder isn't live on the master branch

**Comment by artielbm** [comment]
I will merge it with the master branch. - Artie

**Comment by artielbm** [comment]
It’s merged now, I added the appropriate links to the CV page, and everything works.  This is also the first time that I have used a pull request to manage the updates.  Thanks. - Artie

From: Arthur Sherman <arthurs@niddk.nih.gov>
Date: Friday, July 24, 2020 at 5:07 PM
To: "artielbm/artielbm.github.io" <reply@reply.github.com>
Subject: Re: [artielbm/artielbm.github.io] Add Corticotroph_JNP and Pituitary_MCE models (#1)

I will merge it with the master branch. - Artie

**Pull request merged**
